name: CI

on:
    push:
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20

            - run: npm install

            - name: linter
              run: npx eslint .
              continue-on-error: true

            - name: linter results
              run: |
                  if npx eslint .; then 
                    echo "::notice:: Linter OK"
                  else 
                    echo "::error:: Linter KO"
                  fi
            - name: test 
              run: npm test
              continue-on-error: true

            - name: test results
              run: |
                  if npm test; then 
                    echo "::notice:: Test OK"
                  else 
                    echo "::error:: Test KO"
                  fi

            - run: npm audit
